name: portfolio
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/news/ic_home.png
    - images/news/ic_home_selected.png
    - images/news/ic_bookmark.png
    - images/news/ic_bookmark_selected.png
    - images/news/ic_search.png
    - images/news/ic_search_selected.png
    - images/news/ic_setting.png
    - images/news/ic_setting_selected.png
    - images/news/ic_apple_border.png
    - images/news/ic_facebook_border.png
    - images/news/ic_email_border.png
    - images/news/ic_google_border.png
    - images/news/ic_twitter_border.png
    - images/news/ic_delete.png
    - images/news/ic_left.png
    - images/news/ic_right.png
    - images/news/ic_notif.png
    - images/news/ic_notif_alert.png
    - images/news/ic_eye_show.png
    - images/news/ic_eye_hide.png
    - images/news/ic_sample.png
    - images/news/ic_sample2.jpg
    - images/news/ic_sample3.jpg
    - images/news/ic_logo.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
